"""add role to users

Revision ID: 43c4966a3de2
Revises: b905523344d9
Create Date: 2026-07-13 07:26:09.994957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43c4966a3de2'
down_revision: Union[str, Sequence[str], None] = 'b905523344d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Phase 1: Expand
    op.add_column(
        "users",
        sa.Column("role", sa.String(length=20), nullable=True,))

    # Phase 2: Backfill existing users
    op.execute("""UPDATE users SET role = 'user' WHERE role is NULL""")

    # Phase 3: Enforce constraint
    op.alter_column("users", "role", nullable=False,)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
